name = "portfolio-cms"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "portfolio_maheskanoko"
database_id = "ecfa160c-6d75-41a1-987f-857039dc4719"
migrations_dir = "migrations"
